name: "Drupal Spoons Composer (php-actions)"
description: "Use the Composer CLI with the Drupal Spoons composer plugin in your Github Actions."

inputs:
  version:
    description: "What version of Composer to use"
    default: latest
    required: false

  php_version:
    description: "What version of PHP to use"
    default: latest
    required: false

  php_extensions:
    description: "Space separated list of extensions to configure with the PHP build (defaults to: gd)"
    default: gd
    required: false

  command:
    description: "Composer command to run"
    required: true
    default: install

  only_args:
    description: "Only run the desired command with this args. Ignoring all other provided arguments"
    required: false

  interaction:
    description: "Whether to ask any interactive questions. Values: 'yes' or 'no'"
    required: false
    default: no

  dev:
    description: "Whether to install dev packages. Values: 'yes' or 'no'"
    required: false
    default: yes

  progress:
    description: "Whether to output download progress"
    required: false
    default: no

  quiet:
    description: "Whether to suppress all messages"
    required: false
    default: no

  args:
    description: "Optional arguments to pass"
    required: false

  ssh_key:
    description: "The private key contents to use for private repositories"
    required: false

  ssh_key_pub:
    description: "The public key contents to use for private repositories"
    required: false

  ssh_domain:
    description: "The domain to gather SSH public keys for (automatic for github.com, gitlab.com, bitbucket.org)"
    required: false

  ssh_port:
    description: Custom port to use in conjunction with ssh_domain
    required: false

  working_dir:
    description: "Use the given directory as working directory"
    required: false

  memory_limit:
    description: "Sets the composer memory limit"
    required: false

  setup_drupal:
    description: "Setup drupal via drupalspoons composer plugin"
    required: false
    default: no

  drupal_core_constraint:
    description: "Drupal core version constraint for the drupal version to install"
    required: false
    default: "^10"

  drupal_spoons_plugin_constraint:
    description: "Drupal spoons composer plugin version constraint"
    required: false
    default: "^2"

  drupal_spoons_composer_file:
    description: "Drupal Spoons composer file name"
    required: false
    default: composer.spoons.json

  drupal_web_root:
    description: "Web root directory"
    required: false
    default: web

  drupal_web_port:
    description: "Listen port for local drupal installation"
    required: false
    default: 9000

  drupal_simpletest_base_url:
    description: "Drupal Simpletest base url"
    required: false
    default: http://localhost

  drupal_simpletest_db:
    description: "Drupal Simpletest Database URI"
    required: false
    default: sqlite://localhost/sites/default/files/.sqlite

outputs:
  full_command:
    description: "The full command passed to docker to run"
    value: ${{ steps.composer_run.outputs.full_command }}

runs:
  using: "composite"
  steps:
    - env:
        ACTION_VERSION: ${{ inputs.version }}
        ACTION_PHP_VERSION: ${{ inputs.php_version }}
        ACTION_PHP_EXTENSIONS: ${{ inputs.php_extensions }}
        ACTION_TOKEN: ${{ github.token }}
        ACTION_COMMAND: ${{ inputs.command }}
        ACTION_ONLY_ARGS: ${{ inputs.only_args }}
        ACTION_INTERACTION: ${{ inputs.interaction }}
        ACTION_DEV: ${{ inputs.dev }}
        ACTION_PROGRESS: ${{ inputs.progress }}
        ACTION_QUIET: ${{ inputs.quiet }}
        ACTION_ARGS: ${{ inputs.args }}
        ACTION_SSH_KEY: ${{ inputs.ssh_key }}
        ACTION_SSH_KEY_PUB: ${{ inputs.ssh_key_pub }}
        ACTION_SSH_DOMAIN: ${{ inputs.ssh_domain }}
        ACTION_SSH_PORT: ${{ inputs.ssh_port }}
        ACTION_WORKING_DIR: ${{ inputs.working_dir }}
        ACTION_MEMORY_LIMIT: ${{ inputs.memory_limit }}
        ACTION_SETUP_DRUPAL: ${{ inputs.setup_drupal }}
        DRUPAL_CORE_CONSTRAINT: ${{ inputs.drupal_core_constraint }}
        COMPOSER_PLUGIN_CONSTRAINT: ${{ inputs.drupal_spoons_plugin_constraint }}
        COMPOSER: ${{ inputs.drupal_spoons_composer_file }}
        WEB_ROOT: ${{ inputs.drupal_web_root }}
        WEB_PORT: ${{ inputs.drupal_web_port }}
        SIMPLETEST_BASE_URL: ${{ inputs.drupal_simpletest_base_url }}
        SIMPLETEST_DB: ${{ inputs.drupal_simpletest_db }}
      id: composer_drupal_spoons_run
      run: |
        set -e
        bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/v2.2.0/php-build.bash) composer
        ${{ github.action_path }}/composer-action.bash
      shell: bash

branding:
  icon: 'package'
  color: 'purple'
